import { RatioType } from './graphql.js';

export const origworld = {
	name: 'Saveurs de Tunisie',
	logo: 'icones/tunisie.jpg',
	money: 0,
	score: 0,
	totalangels: 0,
	activeangels: 0,
	angelbonus: 2,
	lastupdate: 0,
	products: [
		{
			id: 1,
			name: 'Chechia',
			logo: 'icones/chechia.jpg',
			cout: 4,
			croissance: 1.07,
			revenu: 1,
			vitesse: 500,
			quantite: 1,
			timeleft: 0,
			managerUnlocked: false,
			paliers: [
				{
					name: 'Chechia traditionnelle',
					logo: 'icones/chechia.jpg',
					seuil: 20,
					idcible: 1,
					ratio: 2,
					typeratio: RatioType.vitesse,
					unlocked: false,
				},
				{
					name: 'Chechia de ceremonie',
					logo: 'icones/chechia.jpg',
					seuil: 75,
					idcible: 1,
					ratio: 2,
					typeratio: RatioType.gain,
					unlocked: false,
				},
				{
					name: 'Chechia royale',
					logo: 'icones/chechia.jpg',
					seuil: 250,
					idcible: 1,
					ratio: 3,
					typeratio: RatioType.gain,
					unlocked: false,
				},
			],
		},
		{
			id: 2,
			name: 'Chicha',
			logo: 'icones/chicha.jpg',
			cout: 60,
			croissance: 1.15,
			revenu: 60,
			vitesse: 3000,
			quantite: 0,
			timeleft: 0,
			managerUnlocked: false,
			paliers: [
				{
					name: 'Chicha en terre cuite',
					logo: 'icones/chicha.jpg',
					seuil: 20,
					idcible: 2,
					ratio: 2,
					typeratio: RatioType.vitesse,
					unlocked: false,
				},
				{
					name: 'Chicha parfume',
					logo: 'icones/chicha.jpg',
					seuil: 75,
					idcible: 2,
					ratio: 2,
					typeratio: RatioType.gain,
					unlocked: false,
				},
				{
					name: 'Chicha des medinas',
					logo: 'icones/chicha.jpg',
					seuil: 250,
					idcible: 2,
					ratio: 3,
					typeratio: RatioType.gain,
					unlocked: false,
				},
			],
		},
		{
			id: 3,
			name: 'Harissa',
			logo: 'icones/harissa.jpg',
			cout: 720,
			croissance: 1.22,
			revenu: 540,
			vitesse: 7000,
			quantite: 0,
			timeleft: 0,
			managerUnlocked: false,
			paliers: [
				{
					name: 'Harissa douce',
					logo: 'icones/harissa.jpg',
					seuil: 20,
					idcible: 3,
					ratio: 2,
					typeratio: RatioType.vitesse,
					unlocked: false,
				},
				{
					name: 'Harissa bien relevee',
					logo: 'icones/harissa.jpg',
					seuil: 75,
					idcible: 3,
					ratio: 2,
					typeratio: RatioType.gain,
					unlocked: false,
				},
				{
					name: 'Harissa artisanale',
					logo: 'icones/harissa.jpg',
					seuil: 250,
					idcible: 3,
					ratio: 3,
					typeratio: RatioType.gain,
					unlocked: false,
				},
			],
		},
		{
			id: 4,
			name: 'Fricassee',
			logo: 'icones/fricassee.jpg',
			cout: 8640,
			croissance: 1.29,
			revenu: 4320,
			vitesse: 15000,
			quantite: 0,
			timeleft: 0,
			managerUnlocked: false,
			paliers: [
				{
					name: 'Fricassee croustillante',
					logo: 'icones/fricassee.jpg',
					seuil: 20,
					idcible: 4,
					ratio: 2,
					typeratio: RatioType.vitesse,
					unlocked: false,
				},
				{
					name: 'Fricassee epicee',
					logo: 'icones/fricassee.jpg',
					seuil: 75,
					idcible: 4,
					ratio: 2,
					typeratio: RatioType.gain,
					unlocked: false,
				},
				{
					name: 'Fricassee de la Marsa',
					logo: 'icones/fricassee.jpg',
					seuil: 250,
					idcible: 4,
					ratio: 3,
					typeratio: RatioType.gain,
					unlocked: false,
				},
			],
		},
		{
			id: 5,
			name: 'Boga',
			logo: 'icones/boga.jpg',
			cout: 103680,
			croissance: 1.36,
			revenu: 34560,
			vitesse: 30000,
			quantite: 0,
			timeleft: 0,
			managerUnlocked: false,
			paliers: [
				{
					name: 'Boga glacee',
					logo: 'icones/boga.jpg',
					seuil: 20,
					idcible: 5,
					ratio: 2,
					typeratio: RatioType.vitesse,
					unlocked: false,
				},
				{
					name: 'Boga pour tous',
					logo: 'icones/boga.jpg',
					seuil: 75,
					idcible: 5,
					ratio: 2,
					typeratio: RatioType.gain,
					unlocked: false,
				},
				{
					name: 'Boga premium',
					logo: 'icones/boga.jpg',
					seuil: 250,
					idcible: 5,
					ratio: 3,
					typeratio: RatioType.gain,
					unlocked: false,
				},
			],
		},
		{
			id: 6,
			name: 'Djeba',
			logo: 'icones/djeba.jpg',
			cout: 1244160,
			croissance: 1.43,
			revenu: 311040,
			vitesse: 60000,
			quantite: 0,
			timeleft: 0,
			managerUnlocked: false,
			paliers: [
				{
					name: 'Djeba brodee',
					logo: 'icones/djeba.jpg',
					seuil: 20,
					idcible: 6,
					ratio: 2,
					typeratio: RatioType.vitesse,
					unlocked: false,
				},
				{
					name: 'Djeba de fete',
					logo: 'icones/djeba.jpg',
					seuil: 75,
					idcible: 6,
					ratio: 2,
					typeratio: RatioType.gain,
					unlocked: false,
				},
				{
					name: 'Djeba de prestige',
					logo: 'icones/djeba.jpg',
					seuil: 250,
					idcible: 6,
					ratio: 3,
					typeratio: RatioType.gain,
					unlocked: false,
				},
			],
		},
	],
	allunlocks: [
		{
			name: 'Le gout du partage',
			logo: 'icones/all.jpg',
			seuil: 30,
			idcible: 0,
			ratio: 2,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Traditions tunisiennes',
			logo: 'icones/all.jpg',
			seuil: 150,
			idcible: 0,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Fierte nationale',
			logo: 'icones/all.jpg',
			seuil: 500,
			idcible: 0,
			ratio: 4,
			typeratio: RatioType.gain,
			unlocked: false,
		},
	],
	upgrades: [
		{
			name: 'Fil de qualite',
			logo: 'icones/chechia.jpg',
			seuil: 1000,
			idcible: 1,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Tabac parfume',
			logo: 'icones/chicha.jpg',
			seuil: 3000,
			idcible: 2,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Piments rouges',
			logo: 'icones/harissa.jpg',
			seuil: 10000,
			idcible: 3,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Pain tabouna',
			logo: 'icones/fricassee.jpg',
			seuil: 25000,
			idcible: 4,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Bulles tunisiennes',
			logo: 'icones/boga.jpg',
			seuil: 50000,
			idcible: 5,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Broderie fine',
			logo: 'icones/djeba.jpg',
			seuil: 100000,
			idcible: 6,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Atelier moderne',
			logo: 'icones/all.jpg',
			seuil: 250000,
			idcible: 0,
			ratio: 2,
			typeratio: RatioType.vitesse,
			unlocked: false,
		},
		{
			name: 'Savoir-faire familial',
			logo: 'icones/all.jpg',
			seuil: 500000,
			idcible: 0,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Saveurs authentiques',
			logo: 'icones/all.jpg',
			seuil: 1000000,
			idcible: 0,
			ratio: 4,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Rayonnement international',
			logo: 'icones/all.jpg',
			seuil: 5000000,
			idcible: 0,
			ratio: 5,
			typeratio: RatioType.gain,
			unlocked: false,
		},
	],
	angelupgrades: [
		{
			name: 'Ange des medinas',
			logo: 'icones/angel.png',
			seuil: 10,
			idcible: 0,
			ratio: 3,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Ange des saveurs',
			logo: 'icones/angel.png',
			seuil: 100,
			idcible: 0,
			ratio: 2,
			typeratio: RatioType.vitesse,
			unlocked: false,
		},
		{
			name: 'Ange du commerce',
			logo: 'icones/angel.png',
			seuil: 1000,
			idcible: 0,
			ratio: 5,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Mutinerie des anges',
			logo: 'icones/angel.png',
			seuil: 10000,
			idcible: -1,
			ratio: 2,
			typeratio: RatioType.ange,
			unlocked: false,
		},
	],
	managers: [
		{
			name: 'Hassen',
			logo: 'icones/manager-chechia.jpg',
			seuil: 10,
			idcible: 1,
			ratio: 0,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Noura',
			logo: 'icones/manager-chicha.jpg',
			seuil: 15000,
			idcible: 2,
			ratio: 0,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Amel',
			logo: 'icones/manager-harissa.jpg',
			seuil: 50000,
			idcible: 3,
			ratio: 0,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Yassine',
			logo: 'icones/manager-fricassee.jpg',
			seuil: 100000,
			idcible: 4,
			ratio: 0,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Sami',
			logo: 'icones/manager-boga.jpg',
			seuil: 250000,
			idcible: 5,
			ratio: 0,
			typeratio: RatioType.gain,
			unlocked: false,
		},
		{
			name: 'Ines',
			logo: 'icones/manager-djeba.jpg',
			seuil: 500000,
			idcible: 6,
			ratio: 0,
			typeratio: RatioType.gain,
			unlocked: false,
		},
	],
};
